#!/usr/bin/env node
// Builds the design galleries from one source, gallery/examples.json, so the
// screenshots, the markdown pages and the HTML pages can never disagree.
// Each example names its banner engine: "v1" examples make up gallery/,
// "v2" examples make up gallery/v2/. The two pages link to each other.
//
//   node scripts/gallery.mjs render [id ...]  screenshot each example to <gallery dir>/img/<id>.png
//                                             (needs playwright: npm i playwright)
//   node scripts/gallery.mjs build            validate, then write README.md + index.html for each gallery
//   node scripts/gallery.mjs build --check    exit 1 if those files are out of date (for CI)
//
// Node standard library only, except `render`, which loads playwright on demand.
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://manual.hu-manity.co/gallery/';
// Per engine: where its gallery lives in this repo, its public URL, and the widget script it renders with.
const ENGINES = {
  v1: { dir: 'gallery', url: SITE, widget: 'https://cdn.hu-manity.co/hu-banner.min.js' },
  v2: { dir: 'gallery/v2', url: `${SITE}v2/`, widget: 'https://cdn.hu-manity.co/v2/hu-banner.min.js' },
};
const WIDGET_ANIMATION_SPEED = '0.3s'; // both widgets' default design.animationSpeed
const PAGE_URL = 'https://example.com/'; // render only: intercepted, never fetched
const GENERATED = 'Generated by scripts/gallery.mjs from gallery/examples.json. Do not edit by hand.';

const all = JSON.parse(readFileSync(join(root, 'gallery', 'examples.json'), 'utf8'));
const examplesOf = (engine) => all.filter((ex) => ex.engine === engine);

// ---------- validation ----------

// Only keys a live app can store and apply, on either engine. Level colours
// (silverColor, goldColor, platinumColor) and levelsOrder are left out on
// purpose: restyling the levels could make "Private" look like the lesser
// choice. Widget-only keys (spacingSize, navigationStyle, ...) are left out
// because copying them to a live app would silently do nothing.
const ALLOWED = new Set([
  'textSize', 'headingSize', 'animationSpeed', 'position', 'displayType', 'marginSize',
  'revokePosition', 'revokeMarginX', 'revokeMarginY', 'animation', 'showDuration',
  'textColor', 'headingColor', 'primaryColor', 'borderColor', 'bannerOpacity',
  'bannerColor', 'btnTextColor', 'btnBorderRadius',
]);
// Every example sets these, so each screenshot shows a complete, intended look
// rather than a mix of the example and the widget defaults.
const REQUIRED = ['bannerOpacity', 'textColor', 'headingColor', 'primaryColor',
  'btnTextColor', 'bannerColor', 'borderColor', 'btnBorderRadius', 'textSize', 'headingSize'];
// The widget has CSS for these values only; anything else renders unstyled.
const ENUMS = {
  position: ['bottom', 'top', 'left', 'right', 'center'],
  displayType: ['floating', 'fixed'],
  animation: ['fade', 'slide'], // as the MCP design schema accepts
  revokePosition: ['bottom-left', 'bottom-right'],
};
// v2 only: the one config key an example may set. It is a config key, not a design key.
const BANNER_STYLES = ['standard', 'compact'];
// Screenshot sizes. Desktop is the default; "phone" shows the narrow-screen layout.
const VIEWPORTS = {
  desktop: { viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 },
  phone: { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 },
};
// The unselected level pills always sit on this background in v1: it is fixed
// in the widget's stylesheet (its inactive-pill colour), and no design key changes it.
const INACTIVE_PILL_BG = '#ffffff';
const HEX = /^#[0-9a-f]{6}$/i; // the widget replaces any other colour format with its default
const LENGTH = /^\d+(\.\d+)?px$/;
const COLOR_KEYS = ['textColor', 'headingColor', 'primaryColor', 'borderColor', 'bannerColor', 'btnTextColor'];
const LENGTH_KEYS = ['textSize', 'headingSize', 'marginSize', 'revokeMarginX', 'revokeMarginY', 'btnBorderRadius'];

// WCAG 2 relative luminance and contrast ratio.
function luminance(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}
// The colour a visitor sees when fg is drawn at `alpha` opacity over bg.
function blend(fg, bg, alpha) {
  return '#' + [1, 3, 5].map((i) => {
    const c = alpha * parseInt(fg.slice(i, i + 2), 16) + (1 - alpha) * parseInt(bg.slice(i, i + 2), 16);
    return Math.round(c).toString(16).padStart(2, '0');
  }).join('');
}

// Every colour pair a visitor has to read on the first layer, as
// [foreground label, hex, background label, hex, minimum ratio].
function contrastPairs(ex) {
  const d = ex.design;
  if (ex.engine === 'v1') {
    // WCAG AA for normal text. The selected level pill renders the btnTextColor
    // label on secondaryColor, which falls back to borderColor in the widget's
    // stylesheet, so a label colour chosen for the button must also be checked
    // on borderColor.
    const pairs = [['textColor', 'bannerColor'], ['headingColor', 'bannerColor'],
      ['btnTextColor', 'primaryColor'], ['btnTextColor', 'borderColor'],
      // The widget's stylesheet also uses primaryColor as a text colour: the
      // Customize, Privacy policy and Do Not Sell links sit on bannerColor.
      ['primaryColor', 'bannerColor']]
      .map(([fg, bg]) => [fg, d[fg], bg, d[bg], 4.5]);
    // The unselected level labels are drawn in borderColor on INACTIVE_PILL_BG.
    pairs.push(['borderColor (unselected level label)', d.borderColor, 'the inactive pill background', INACTIVE_PILL_BG, 4.5]);
    return pairs;
  }
  // v2: every element below sits directly on the panel, which is bannerColor.
  const pairs = [
    ['textColor', d.textColor, 'bannerColor (body text)', d.bannerColor, 4.5], // the message paragraph
    ['headingColor', d.headingColor, 'bannerColor (heading)', d.bannerColor, 4.5], // the notice heading
    ['headingColor', d.headingColor, 'bannerColor (unselected level label)', d.bannerColor, 4.5], // level pills are transparent
    ['textColor', d.textColor, 'bannerColor (Customize)', d.bannerColor, 4.5], // Customize is a transparent button
    ['primaryColor', d.primaryColor, 'bannerColor (links)', d.bannerColor, 4.5], // Privacy policy, Do Not Sell, and compact's phone Customize link
    ['btnTextColor', d.btnTextColor, 'primaryColor (selected level label)', d.primaryColor, 4.5], // a chosen pill fills with primaryColor
    ['borderColor', d.borderColor, 'bannerColor (level pill border)', d.bannerColor, 3], // non-text: WCAG 1.4.11 asks 3:1
  ];
  // The Global Privacy Control note, both styles: shown when the visitor sends GPC. Drawn at 0.85 opacity.
  if (HEX.test(d.textColor ?? '') && HEX.test(d.bannerColor ?? '')) {
    pairs.push(['textColor at 0.85 opacity', blend(d.textColor, d.bannerColor, 0.85), 'bannerColor (GPC note)', d.bannerColor, 4.5]);
  }
  // The site's domain, top left: standard only (compact puts the heading there). Drawn at 0.7 opacity.
  if (ex.config?.bannerStyle === 'standard' && HEX.test(d.textColor ?? '') && HEX.test(d.bannerColor ?? '')) {
    pairs.push(['textColor at 0.7 opacity', blend(d.textColor, d.bannerColor, 0.7), 'bannerColor (site domain)', d.bannerColor, 4.5]);
  }
  return pairs;
}

const imageRel = (ex) => `${ENGINES[ex.engine].dir}/img/${ex.id}.png`;
const imagePath = (ex) => join(root, imageRel(ex));

function validate({ needImages }) {
  const errors = [];
  const ids = new Set();
  for (const ex of all) {
    const where = `example "${ex.id}"`;
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(ex.id ?? '')) errors.push(`${where}: id must be a lowercase slug`);
    if (ids.has(ex.id)) errors.push(`${where}: duplicate id`);
    ids.add(ex.id);
    if (!(ex.engine in ENGINES)) {
      errors.push(`${where}: engine must be one of ${Object.keys(ENGINES).join('|')}`);
      continue; // everything below depends on the engine
    }
    for (const f of ['title', 'caption', 'alt']) {
      if (typeof ex[f] !== 'string' || !ex[f].trim()) errors.push(`${where}: missing ${f}`);
    }
    for (const f of ['background', 'text', 'accent']) {
      if (!HEX.test(ex.site?.[f] ?? '')) errors.push(`${where}: site.${f} must be #rrggbb`);
    }
    if ('viewport' in ex && ex.viewport !== 'phone') errors.push(`${where}: viewport must be "phone" (or left out for desktop)`);
    // bannerStyle exists only in v2; v1 would ignore it, so a v1 example carrying it would mislead.
    if (ex.engine === 'v1' && 'config' in ex) errors.push(`${where}: config is v2 only (v1 has no bannerStyle)`);
    if (ex.engine === 'v2') {
      const c = ex.config ?? {};
      for (const k of Object.keys(c)) {
        if (k !== 'bannerStyle') errors.push(`${where}: config key "${k}" is not allowed (only bannerStyle)`);
      }
      if (!BANNER_STYLES.includes(c.bannerStyle)) errors.push(`${where}: config.bannerStyle must be one of ${BANNER_STYLES.join('|')}`);
    }
    const d = ex.design ?? {};
    for (const k of Object.keys(d)) {
      if (!ALLOWED.has(k)) errors.push(`${where}: design key "${k}" is not allowed`);
    }
    for (const k of REQUIRED) {
      if (!(k in d)) errors.push(`${where}: design.${k} is required`);
    }
    for (const [k, values] of Object.entries(ENUMS)) {
      if (k in d && !values.includes(d[k])) errors.push(`${where}: design.${k} must be one of ${values.join('|')}`);
    }
    for (const k of COLOR_KEYS) {
      if (k in d && !HEX.test(d[k])) errors.push(`${where}: design.${k} must be #rrggbb`);
    }
    for (const k of LENGTH_KEYS) {
      if (k in d && !LENGTH.test(d[k])) errors.push(`${where}: design.${k} must be a px length`);
    }
    if ('animationSpeed' in d && !/^\d+(\.\d+)?s$/.test(d.animationSpeed)) errors.push(`${where}: design.animationSpeed must be in seconds`);
    if ('showDuration' in d && typeof d.showDuration !== 'boolean') errors.push(`${where}: design.showDuration must be true or false`);
    // Below 1, the page shows through the banner, so the contrast figures
    // below would not be what a visitor actually sees.
    if (d.bannerOpacity !== 1) errors.push(`${where}: design.bannerOpacity must be 1`);
    for (const [fg, fgHex, bg, bgHex, min] of contrastPairs({ ...ex, design: d })) {
      if (!HEX.test(fgHex ?? '') || !HEX.test(bgHex ?? '')) continue;
      const ratio = contrast(fgHex, bgHex);
      if (ratio < min) errors.push(`${where}: ${fg} on ${bg} contrast is ${ratio.toFixed(2)}:1, below WCAG AA ${min}:1`);
    }
    // The pages show the image; a missing one would publish a broken gallery.
    if (needImages && !existsSync(imagePath(ex))) errors.push(`${where}: missing ${imageRel(ex)} (run: node scripts/gallery.mjs render ${ex.id})`);
  }
  // A PNG with no example would be published to the site but shown nowhere.
  if (needImages) {
    for (const [engine, { dir }] of Object.entries(ENGINES)) {
      const own = new Set(examplesOf(engine).map((ex) => ex.id));
      const imgDir = join(root, dir, 'img');
      for (const f of existsSync(imgDir) ? readdirSync(imgDir) : []) {
        if (f.endsWith('.png') && !own.has(f.slice(0, -4))) errors.push(`orphan image ${dir}/img/${f}: no ${engine} example has id "${f.slice(0, -4)}" (delete it)`);
      }
    }
  }
  if (errors.length) {
    console.error('gallery: validation failed\n  ' + errors.join('\n  '));
    process.exit(1);
  }
}

// Width and height from the PNG header (IHDR), so <img> sizes always match the file.
function pngSize(ex) {
  const buf = readFileSync(imagePath(ex));
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

// ---------- shared text ----------

// The count in generated copy comes from the source, so adding an example never leaves it stale.
function count(n) {
  const word = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'][n] ?? String(n);
  return word[0].toUpperCase() + word.slice(1);
}

// What each JSON block shows: v1 a design object; v2 the design plus its config.bannerStyle,
// in the same shape account.previewDesignChange and account.updateDesign take.
const exampleJson = (ex) => JSON.stringify(ex.engine === 'v1' ? ex.design : { config: ex.config, design: ex.design }, null, 2);

const APPLY_V1 = [
  'A `design` block set on your own page is overwritten by your app\'s published configuration a moment after the banner loads. To use one of these designs on a live banner:',
  '',
  '- **Dashboard:** set the same values in your app\'s banner design settings, then publish.',
  '- **MCP server:** call `account.previewDesignChange` with your AppID and the `design` object, show the before/after to the site owner, then call `account.updateDesign` with the same object and the returned `previewToken`.',
  '',
  'Never add a `design` block to the install snippet. To derive a design from your own site\'s colours instead, follow [`skills/match-site-design/SKILL.md`](../skills/match-site-design/SKILL.md).',
];

// Each gallery's text, as markdown. The HTML page renders the same lines.
const TEXT = {
  v1: {
    title: 'Banner design gallery',
    intro: (n) => `${count(n)} example designs for the Cookie Compliance banner. Each one is a screenshot of the real widget in preview mode, using one of its real layouts. The build checks body text and headings against the banner colour, and the button label, the selected and unselected level labels and the links against their backgrounds, at WCAG AA (4.5:1).`,
    desc: (n) => `${count(n)} example Cookie Compliance consent banner designs, each with a screenshot and the exact design JSON, with text, button, level label and link colours checked against WCAG AA.`,
    // These designs are for the default banner; the other gallery covers the opt-in v2 one.
    sibling: { lead: 'These designs are for the v1 banner, the default.', text: 'For the opt-in v2 banner and its compact style, see the', name: 'v2 banner design gallery', md: 'v2/README.md', html: 'v2/', footer: 'v2 banner designs:' },
    before: [],
    after: [['Apply a design to your live banner', APPLY_V1]],
  },
  v2: {
    title: 'v2 banner design gallery',
    intro: (n) => `${count(n)} example designs for the v2 Cookie Compliance banner, in both of its styles, standard and compact. Each one is a screenshot of the real v2 widget showing that design. The build checks every colour pair a visitor reads on the v2 banner's first layer at WCAG AA (4.5:1), and the level pill borders at 3:1.`,
    desc: (n) => `${count(n)} example designs for the v2 Cookie Compliance consent banner, in standard and compact styles, each with a screenshot and the exact design and config JSON, with every first-layer colour pair checked against WCAG AA.`,
    sibling: { lead: 'These designs are for the v2 banner, which is opt-in.', text: 'For the default v1 banner, see the', name: 'v1 banner design gallery', md: '../README.md', html: '../', footer: 'v1 (default) banner designs:' },
    before: [
      ['What v2 is', [
        'v2 is the new banner engine. It is opt-in, per app: an app uses the v1 banner, the default, until its owner switches it to v2, and it can be switched back the same way.',
        '',
        'The v2 first layer offers the consent levels as buttons, Private, Personalized and (when the app offers three choices) Balanced, with Customize last. There is no Accept or Save button: choosing a level is the choice, and nothing is selected until the visitor picks one. Customize opens the categories.',
      ]],
      ['Standard and compact', [
        'v2 has two styles, set with `config.bannerStyle` (a config key, not a design key):',
        '',
        '- **Standard** (the default): the site\'s domain in the top row, the heading and message below it, then the level buttons, then Customize. Balanced shows only when the app offers three choices (its number-of-choices setting); with two, standard shows Private and Personalized. On screens 480px wide or less the level buttons and Customize stack into one full-width column.',
        '- **Compact:** the first layer offers Private and Personalized only (Customize still lists every category), and the heading moves into the top row in place of the domain. At `position` top or bottom with `displayType` fixed, on screens 1200px wide or more, the whole banner is a single-row bar. On screens 480px wide or less, Customize becomes an underlined link in `primaryColor`.',
        '',
        'The examples use the default behaviour settings. On a live banner, the number of choices, the close button and which links show depend on the app\'s settings and the visitor\'s region.',
      ]],
    ],
    after: [
      ['Switch an app to v2', [
        '1. **Dashboard:** open the app, go to Configuration → Design, and find the last card, **Banner engine**. Set **Engine version** to **New**. It saves itself.',
        '2. **WordPress plugin:** version 3.1.11 or later picks the change up at its next check-in. Nothing to paste.',
        '3. **Hand-pasted snippet:** go to Integrations, copy the updated snippet (it loads the v2 script) and replace the old one on your site.',
        '4. Once the app is on v2, set **Banner style** to Compact if you want the compact style, then click **Publish Now** (unlike Engine version, this setting does not save itself). Standard is the default.',
        '',
        'To switch back to v1, follow the same steps and set the engine version back. For a hand-pasted snippet, paste the updated snippet again.',
      ]],
      ['Apply a design to your live banner', [
        'A `design` block set on your own page is overwritten by your app\'s published configuration a moment after the banner loads. To use one of these designs on a live v2 banner:',
        '',
        '- **Dashboard:** set the same values in your app\'s banner design settings, and the Banner style, then click **Publish Now**.',
        '- **MCP server:** call `account.previewDesignChange` with your AppID and both objects from the example, `design` and `config` (which carries `bannerStyle`), show the before/after to the site owner, then call `account.updateDesign` with the same objects and the returned `previewToken`.',
        '',
        'Never add a `design` block to the install snippet.',
      ]],
      ['Previewing', [
        'The MCP preview tools show the v1 banner only, and `demo.suggestDesign` checks colours against the v1 banner\'s pairs. To apply a v2 design, use `account.previewDesignChange` then `account.updateDesign` (with `design` and `config.bannerStyle`), or the dashboard.',
        '',
        'If you derive your own v2 colours, check these pairs at 4.5:1 with `bannerOpacity` at 1:',
        '',
        '- `textColor` on `bannerColor`: the message and the Customize label.',
        '- `headingColor` on `bannerColor`: the heading and the level button labels.',
        '- `primaryColor` on `bannerColor`: the links, and compact\'s Customize link on phones.',
        '- `textColor` at 0.7 opacity over `bannerColor`: the site\'s domain (standard only).',
        '- `textColor` at 0.85 opacity over `bannerColor`: the note shown to a visitor who sends Global Privacy Control.',
        '- `btnTextColor` on `primaryColor`: a chosen level button.',
        '- `borderColor` on `bannerColor`, at 3:1: the level button borders.',
      ]],
    ],
  },
};

// Markdown for the cross-link to the other gallery.
const siblingMd = (s) => `${s.lead} ${s.text} [${s.name}](${s.md}).`;

// ---------- README.md ----------

function readme(engine) {
  const t = TEXT[engine];
  const examples = examplesOf(engine);
  const out = [`<!-- ${GENERATED} -->`, '', `# ${t.title}`, '', t.intro(examples.length), '', siblingMd(t.sibling), ''];
  for (const [heading, lines] of t.before) out.push(`## ${heading}`, '', ...lines, '');
  for (const ex of examples) {
    out.push(`## ${ex.title}`, '', `![${ex.alt}](img/${ex.id}.png)`, '', ex.caption, '',
      '```json', exampleJson(ex), '```', '');
  }
  for (const [heading, lines] of t.after) out.push(`## ${heading}`, '', ...lines, '');
  return out.join('\n');
}

// ---------- index.html ----------

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
// Inline markdown used in the shared text: `code`, **bold**, [text](href).
const md = (s) => esc(s)
  .replace(/\[`([^`]+)`\]\(([^)]+)\)/g, '<a href="$2"><code>$1</code></a>')
  .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

// Markdown lines -> HTML blocks: runs of "- " become a <ul>, runs of "1. " an <ol>, other lines a <p>.
function blocksHtml(lines) {
  const out = [];
  let list = null;
  const close = () => { if (list) out.push(`    </${list}>`); list = null; };
  for (const line of lines) {
    const kind = line.startsWith('- ') ? 'ul' : /^\d+\. /.test(line) ? 'ol' : null;
    if (kind) {
      if (list !== kind) { close(); out.push(`    <${kind}>`); list = kind; }
      out.push(`      <li>${md(line.replace(/^(- |\d+\. )/, ''))}</li>`);
    } else {
      close();
      if (line) out.push(`    <p>${md(line)}</p>`);
    }
  }
  close();
  return out.join('\n');
}

const sectionHtml = ([heading, lines]) => `  <section class="apply">
    <h2>${esc(heading)}</h2>
${blocksHtml(lines)}
  </section>
`;

function html(engine) {
  const t = TEXT[engine];
  const { url } = ENGINES[engine];
  const other = ENGINES[engine === 'v1' ? 'v2' : 'v1'].url;
  const examples = examplesOf(engine);
  const title = `${t.title} — Cookie Compliance`;
  const desc = t.desc(examples.length);
  const ogImage = `${url}img/${examples[0].id}.png`;
  const ogSize = pngSize(examples[0]);
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ImageGallery',
    name: t.title,
    description: desc,
    url,
    relatedLink: other, // the other engine's gallery
    image: examples.map((ex) => ({
      '@type': 'ImageObject',
      name: ex.title,
      caption: ex.alt,
      contentUrl: `${url}img/${ex.id}.png`,
    })),
  };
  const figures = examples.map((ex, i) => {
    const { width, height } = pngSize(ex);
    const lazy = i === 0 ? '' : ' loading="lazy"';
    return [
      `    <figure id="${ex.id}">`,
      `      <img src="img/${ex.id}.png" alt="${esc(ex.alt)}" width="${width}" height="${height}"${lazy}>`,
      '      <details>',
      `        <summary>${engine === 'v1' ? 'Design JSON' : 'Design and config JSON'}</summary>`,
      `        <pre><code>${esc(exampleJson(ex))}</code></pre>`,
      '      </details>',
      `      <figcaption><strong>${esc(ex.title)}</strong><span class="desc">${esc(ex.caption)}</span></figcaption>`,
      '    </figure>',
    ].join('\n');
  });
  const s = t.sibling;
  return `<!doctype html>
<!-- ${GENERATED} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${url}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:type" content="website">
<meta property="og:url" content="${url}">
<meta property="og:site_name" content="Cookie Compliance Agent Manual">
<meta property="og:image" content="${ogImage}">
<meta property="og:image:alt" content="${esc(examples[0].alt)}">
<meta property="og:image:width" content="${ogSize.width}">
<meta property="og:image:height" content="${ogSize.height}">
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2).replace(/</g, '\\u003c')}
</script>
<style>
  :root {
    color-scheme: light dark;
    --accent: #20c19e;
    --link: #0f7a63; /* #20c19e is 2.29:1 on white; this is 5.27:1 */
    --bg: #ffffff;
    --fg: #1a1f24;
    --muted: #5a6570;
    --border: #e3e7ea;
    --code-bg: rgba(32,193,158,0.1);
    padding-top: env(safe-area-inset-top, 0px);
    padding-bottom: env(safe-area-inset-bottom, 0px);
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg: #14181c;
      --fg: #eef1f3;
      --muted: #9aa5ad;
      --border: #2a3138;
      --code-bg: rgba(32,193,158,0.15);
      --link: #20c19e;
    }
  }
  :root[data-theme="dark"] {
    --bg: #14181c;
    --fg: #eef1f3;
    --muted: #9aa5ad;
    --border: #2a3138;
    --code-bg: rgba(32,193,158,0.15);
    --link: #20c19e;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    line-height: 1.55;
  }
  main {
    max-width: 76rem;
    margin: 0 auto;
    padding: 3rem 1.25rem 4rem;
  }
  h1 { font-size: 1.6rem; margin: 0 0 0.5rem; }
  .tagline { color: var(--muted); margin: 0 0 2rem; font-size: 1.05rem; max-width: 42rem; }
  .sibling { margin: -1rem 0 2rem; padding: 0.6rem 1rem; max-width: 42rem; border-left: 2px solid var(--accent); background: var(--code-bg); border-radius: 0 6px 6px 0; }
  h2 { font-size: 1.1rem; margin: 2.25rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; }
  a { color: var(--link); text-decoration: none; font-weight: 600; }
  p a, li a, footer a { text-decoration: underline; } /* in-text links: not colour alone */
  a:hover { text-decoration: underline; }
  .back { display: inline-block; margin-bottom: 1.5rem; font-size: 0.92rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 32rem), 1fr)); gap: 2rem; }
  figure { margin: 0; }
  figure img { display: block; width: 100%; height: auto; border: 1px solid var(--border); border-radius: 6px; }
  figcaption { margin: 0.6rem 0 0.4rem; padding-left: 1rem; border-left: 2px solid var(--accent); }
  .desc { display: block; color: var(--muted); font-weight: 400; font-size: 0.92rem; margin-top: 0.15rem; }
  summary { cursor: pointer; color: var(--muted); font-size: 0.9rem; }
  pre { background: var(--code-bg); padding: 0.75rem 1rem; border-radius: 6px; overflow-x: auto; font-size: 0.85rem; }
  code { background: var(--code-bg); padding: 0.1em 0.4em; border-radius: 4px; font-size: 0.9em; }
  pre code { background: none; padding: 0; font-size: inherit; }
  .apply { max-width: 42rem; }
  .apply ul { padding-left: 1.25rem; }
  .apply li { margin: 0.4rem 0; }
  footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.9rem; }
  footer a { font-weight: 400; }
</style>
</head>
<body>
<main>
  <a class="back" href="/">&larr; Cookie Compliance Agent Manual</a>
  <h1>${esc(t.title)}</h1>
  <p class="tagline">${esc(t.intro(examples.length))}</p>
  <p class="sibling">${esc(s.lead)} ${esc(s.text)} <a href="${s.html}">${esc(s.name)}</a>.</p>

${t.before.map(sectionHtml).join('\n')}${t.before.length ? '\n' : ''}  <div class="grid">
${figures.join('\n')}
  </div>

${t.after.map(sectionHtml).join('\n')}
  <footer>
    Cookie Compliance is a product of <a href="https://hu-manity.co">Hu-manity.co</a>.
    Machine-readable version: <a href="README.md">${ENGINES[engine].dir}/README.md</a>.
    ${esc(s.footer)} <a href="${s.html}">${esc(s.name)}</a>.
  </footer>
</main>
</body>
</html>
`;
}

// ---------- build ----------

function build(check) {
  validate({ needImages: true });
  let stale = false;
  const written = [];
  for (const [engine, { dir }] of Object.entries(ENGINES)) {
    for (const [name, content] of Object.entries({ 'README.md': readme(engine), 'index.html': html(engine) })) {
      const rel = `${dir}/${name}`;
      const path = join(root, rel);
      if (check) {
        if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
          console.error(`stale: ${rel} does not match gallery/examples.json (run: node scripts/gallery.mjs build)`);
          stale = true;
        }
      } else {
        writeFileSync(path, content);
        written.push(rel);
      }
    }
  }
  if (stale) process.exit(1);
  console.log(check ? 'gallery: up to date' : `gallery: wrote ${written.join(', ')}`);
}

// ---------- render ----------

// v2 renders with no preview mode: it needs an appID and fetches that app's
// published configuration. The render answers that one request itself, with
// the example's own design and bannerStyle, and blocks every other request.
const V2_CONFIG_PATH = '/api/designer/user-design-live';
const v2Config = (ex) => ({
  status: 200,
  data: {
    DefaultLanguage: 'en',
    BannerConfigJSON: { ...ex.config }, // public-ok: field name in the public widget's config response
    UserDesignJSON: { ...ex.design }, // public-ok: field name in the public widget's config response
    // The widget's built-in English copy, plus a placeholder privacy policy so the link pair is on screen.
    DefaultUserTextJSON: { privacyPolicyUrl: 'https://example.com/privacy' },
    LanguageUserTextJSON: {},
  },
});

// A generic placeholder site in the example's own colours, so each screenshot
// shows the banner in context. The widget script is the only external URL.
function mockPage(ex) {
  const { background: bg, text, accent } = ex.site;
  // Mock call-to-action label: black or white, whichever reads better on the accent.
  const ctaText = contrast('#000000', accent) >= contrast('#ffffff', accent) ? '#000000' : '#ffffff';
  const huOptions = ex.engine === 'v1'
    ? { currentLanguage: 'en', blocking: true, globalCookie: false, design: ex.design, previewMode: true }
    // forceShow: always show the banner, and record nothing.
    : { appID: 'gallery-demo', blocking: true, blockingEngine: true, forceShow: true };
  const para = 'Hand-picked goods for everyday life, shipped from our small workshop. Every item is checked before it leaves, and every order arrives in recycled packaging.';
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<script>var huOptions = ${JSON.stringify(huOptions)};</script>
<script src="${ENGINES[ex.engine].widget}" charset="utf-8"></script>
<style>
  body { margin: 0; background: ${bg}; color: ${text}; font-family: Georgia, "Times New Roman", serif; }
  header { display: flex; align-items: center; justify-content: space-between; padding: 22px 64px; border-bottom: 1px solid ${text}22; }
  .mark { font-size: 24px; font-weight: 700; letter-spacing: 0.02em; }
  nav a { color: ${text}; text-decoration: none; margin-left: 28px; font-family: system-ui, sans-serif; font-size: 15px; }
  .hero { padding: 72px 64px 40px; max-width: 760px; }
  .hero h1 { font-size: 46px; line-height: 1.15; margin: 0 0 18px; }
  .hero p { font-size: 19px; line-height: 1.6; margin: 0 0 26px; opacity: 0.85; }
  .cta { display: inline-block; background: ${accent}; color: ${ctaText}; padding: 12px 26px; border-radius: 4px; font-family: system-ui, sans-serif; font-weight: 600; }
  .body { padding: 0 64px; max-width: 760px; font-size: 17px; line-height: 1.7; opacity: 0.8; }
  @media (max-width: 480px) {
    header { padding: 16px 20px; }
    nav { display: none; }
    .hero { padding: 36px 20px 24px; }
    .hero h1 { font-size: 32px; }
    .body { padding: 0 20px; }
  }
</style>
</head>
<body>
<header><span class="mark">Example Store</span><nav><a href="#">Shop</a><a href="#">Journal</a><a href="#">About</a><a href="#">Contact</a></nav></header>
<section class="hero"><h1>Simple things, made well.</h1><p>${para}</p><span class="cta">Browse the collection</span></section>
<section class="body"><p>${para}</p><p>${para}</p><p>${para}</p></section>
</body>
</html>`;
}

async function render(ids) {
  validate({ needImages: false }); // never screenshot a design the build would reject
  let playwright;
  try {
    playwright = createRequire(import.meta.url)('playwright');
  } catch {
    console.error('gallery render needs playwright. Install it with: npm i playwright (then: npx playwright install chromium)');
    process.exit(1);
  }
  const unknown = ids.filter((id) => !all.some((ex) => ex.id === id));
  if (unknown.length) {
    console.error(`gallery: unknown example id(s): ${unknown.join(', ')}`);
    process.exit(1);
  }
  const chosen = ids.length ? all.filter((ex) => ids.includes(ex.id)) : all;
  const browser = await playwright.chromium.launch();
  // The v1 widget does not start for automated browsers: it checks
  // navigator.webdriver and a "HeadlessChrome/" user agent. Present as a normal
  // desktop Chrome so the preview renders. (v2 checks neither; this is harmless there.)
  const userAgent = `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browser.version()} Safari/537.36`;
  let failed = false;
  try {
    for (const ex of chosen) {
      const context = await browser.newContext({ ...VIEWPORTS[ex.viewport ?? 'desktop'], userAgent });
      await context.addInitScript(() => Object.defineProperty(Navigator.prototype, 'webdriver', { get: () => false }));
      const page = await context.newPage();
      // Served from a placeholder origin, not page.setContent: about:blank has no
      // cookie access, and the widget stops when reading document.cookie throws.
      if (ex.engine === 'v1') {
        await page.route(PAGE_URL, (route) => route.fulfill({ contentType: 'text/html', body: mockPage(ex) }));
      } else {
        await page.route('**/*', (route) => {
          const url = route.request().url();
          if (url === PAGE_URL) return route.fulfill({ contentType: 'text/html', body: mockPage(ex) });
          if (url === ENGINES.v2.widget) return route.continue();
          if (new URL(url).pathname === V2_CONFIG_PATH) return route.fulfill({ contentType: 'application/json', body: JSON.stringify(v2Config(ex)) });
          return route.abort();
        });
      }
      try {
        await page.goto(PAGE_URL, { waitUntil: 'load' });
        // A visitor's Global Privacy Control signal changes what the v2 banner shows.
        if (await page.evaluate(() => navigator.globalPrivacyControl === true)) throw new Error('the browser is sending Global Privacy Control');
        // The banner's root container is #hu; wait inside it, not on the document.
        const banner = page.locator('#hu');
        await banner.waitFor({ state: 'visible', timeout: 20000 });
        await banner.locator('button').first().waitFor({ state: 'visible', timeout: 10000 });
        // Let the entrance animation finish: its length plus a margin, at least 1s.
        const speedMs = parseFloat(ex.design.animationSpeed ?? WIDGET_ANIMATION_SPEED) * 1000;
        await page.waitForTimeout(Math.max(1000, speedMs + 500));
        mkdirSync(dirname(imagePath(ex)), { recursive: true });
        await page.screenshot({ path: imagePath(ex) });
        console.log(`rendered ${imageRel(ex)}`);
      } catch (err) {
        console.error(`gallery: banner did not render for "${ex.id}": ${err.message.split('\n')[0]}`);
        failed = true;
      }
      await context.close();
    }
  } finally {
    await browser.close();
  }
  if (failed) process.exit(1);
}

// ---------- main ----------

const [cmd, ...args] = process.argv.slice(2);
if (cmd === 'build') build(args.includes('--check'));
else if (cmd === 'render') await render(args);
else {
  console.error('usage: node scripts/gallery.mjs build [--check] | render [id ...]');
  process.exit(2);
}
