#!/usr/bin/env node
// Builds the design gallery from one source, gallery/examples.json, so the
// screenshots, the markdown page and the HTML page can never disagree.
//
//   node scripts/gallery.mjs render [id ...]  screenshot each example to gallery/img/<id>.png
//                                             (needs playwright: npm i playwright)
//   node scripts/gallery.mjs build            validate, then write gallery/README.md + index.html
//   node scripts/gallery.mjs build --check    exit 1 if those files are out of date (for CI)
//
// Node standard library only, except `render`, which loads playwright on demand.
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'gallery');
const SITE = 'https://manual.hu-manity.co/gallery/';
const WIDGET = 'https://cdn.hu-manity.co/hu-banner.min.js';
const WIDGET_ANIMATION_SPEED = '0.3s'; // the widget's default design.animationSpeed
const PAGE_URL = 'https://example.com/'; // render only: intercepted, never fetched
const GENERATED = 'Generated by scripts/gallery.mjs from gallery/examples.json. Do not edit by hand.';

const examples = JSON.parse(readFileSync(join(dir, 'examples.json'), 'utf8'));

// ---------- validation ----------

// Only keys a live app can store and apply. Level colours (silverColor,
// goldColor, platinumColor) and levelsOrder are left out on purpose: restyling
// the levels could make "Private" look like the lesser choice. Widget-only keys
// (spacingSize, navigationStyle, ...) are left out because copying them to a
// live app would silently do nothing.
const ALLOWED = new Set([
  'textSize', 'headingSize', 'animationSpeed', 'position', 'displayType', 'marginSize',
  'revokePosition', 'revokeMarginX', 'revokeMarginY', 'animation', 'showDuration',
  'textColor', 'headingColor', 'primaryColor', 'borderColor', 'bannerOpacity',
  'bannerColor', 'btnTextColor', 'btnBorderRadius',
]);
// Every example sets these, so each screenshot shows a complete, intended look
// rather than a mix of the example and the widget defaults.
const REQUIRED = ['bannerOpacity', 'textColor', 'headingColor', 'primaryColor',
  'btnTextColor', 'bannerColor', 'borderColor', 'btnBorderRadius', 'textSize', 'headingSize'];
// The widget has CSS for these values only; anything else renders unstyled.
const ENUMS = {
  position: ['bottom', 'top', 'left', 'right', 'center'],
  displayType: ['floating', 'fixed'],
  animation: ['fade', 'slide'], // as the MCP design schema accepts
  revokePosition: ['bottom-left', 'bottom-right'],
};
// The unselected level pills always sit on this background: it is fixed in the
// widget's stylesheet (its inactive-pill colour), and no design key changes it.
const INACTIVE_PILL_BG = '#ffffff';
const HEX = /^#[0-9a-f]{6}$/i; // the widget replaces any other colour format with its default
const LENGTH = /^\d+(\.\d+)?px$/;
const COLOR_KEYS = ['textColor', 'headingColor', 'primaryColor', 'borderColor', 'bannerColor', 'btnTextColor'];
const LENGTH_KEYS = ['textSize', 'headingSize', 'marginSize', 'revokeMarginX', 'revokeMarginY', 'btnBorderRadius'];

// WCAG 2 relative luminance and contrast ratio.
function luminance(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

function validate({ needImages }) {
  const errors = [];
  const ids = new Set();
  for (const ex of examples) {
    const where = `example "${ex.id}"`;
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(ex.id ?? '')) errors.push(`${where}: id must be a lowercase slug`);
    if (ids.has(ex.id)) errors.push(`${where}: duplicate id`);
    ids.add(ex.id);
    for (const f of ['title', 'caption', 'alt']) {
      if (typeof ex[f] !== 'string' || !ex[f].trim()) errors.push(`${where}: missing ${f}`);
    }
    for (const f of ['background', 'text', 'accent']) {
      if (!HEX.test(ex.site?.[f] ?? '')) errors.push(`${where}: site.${f} must be #rrggbb`);
    }
    const d = ex.design ?? {};
    for (const k of Object.keys(d)) {
      if (!ALLOWED.has(k)) errors.push(`${where}: design key "${k}" is not allowed`);
    }
    for (const k of REQUIRED) {
      if (!(k in d)) errors.push(`${where}: design.${k} is required`);
    }
    for (const [k, values] of Object.entries(ENUMS)) {
      if (k in d && !values.includes(d[k])) errors.push(`${where}: design.${k} must be one of ${values.join('|')}`);
    }
    for (const k of COLOR_KEYS) {
      if (k in d && !HEX.test(d[k])) errors.push(`${where}: design.${k} must be #rrggbb`);
    }
    for (const k of LENGTH_KEYS) {
      if (k in d && !LENGTH.test(d[k])) errors.push(`${where}: design.${k} must be a px length`);
    }
    if ('animationSpeed' in d && !/^\d+(\.\d+)?s$/.test(d.animationSpeed)) errors.push(`${where}: design.animationSpeed must be in seconds`);
    if ('showDuration' in d && typeof d.showDuration !== 'boolean') errors.push(`${where}: design.showDuration must be true or false`);
    // Below 1, the page shows through the banner, so the contrast figures
    // below would not be what a visitor actually sees.
    if (d.bannerOpacity !== 1) errors.push(`${where}: design.bannerOpacity must be 1`);
    // WCAG AA for normal text: every pair a visitor has to read. The selected
    // level pill renders the btnTextColor label on secondaryColor, which falls
    // back to borderColor in the widget's stylesheet, so a
    // label colour chosen for the button must also be checked on borderColor.
    const pairs = [['textColor', 'bannerColor'], ['headingColor', 'bannerColor'],
      ['btnTextColor', 'primaryColor'], ['btnTextColor', 'borderColor'],
      // The widget's stylesheet also uses primaryColor as a text colour: the
      // Customize, Privacy policy and Do Not Sell links sit on bannerColor.
      ['primaryColor', 'bannerColor']]
      .map(([fg, bg]) => [fg, d[fg], bg, d[bg]]);
    // The unselected level labels are drawn in borderColor on INACTIVE_PILL_BG.
    pairs.push(['borderColor (unselected level label)', d.borderColor, 'the inactive pill background', INACTIVE_PILL_BG]);
    for (const [fg, fgHex, bg, bgHex] of pairs) {
      if (!HEX.test(fgHex ?? '') || !HEX.test(bgHex ?? '')) continue;
      const ratio = contrast(fgHex, bgHex);
      if (ratio < 4.5) errors.push(`${where}: ${fg} on ${bg} contrast is ${ratio.toFixed(2)}:1, below WCAG AA 4.5:1`);
    }
    // The pages show the image; a missing one would publish a broken gallery.
    if (needImages && !existsSync(imagePath(ex.id))) errors.push(`${where}: missing gallery/img/${ex.id}.png (run: node scripts/gallery.mjs render ${ex.id})`);
  }
  // A PNG with no example would be published to the site but shown nowhere.
  if (needImages) {
    for (const f of readdirSync(join(dir, 'img'))) {
      if (f.endsWith('.png') && !ids.has(f.slice(0, -4))) errors.push(`orphan image gallery/img/${f}: no example has id "${f.slice(0, -4)}" (delete it)`);
    }
  }
  if (errors.length) {
    console.error('gallery: validation failed\n  ' + errors.join('\n  '));
    process.exit(1);
  }
}

const imagePath = (id) => join(dir, 'img', `${id}.png`);

// Width and height from the PNG header (IHDR), so <img> sizes always match the file.
function pngSize(id) {
  const buf = readFileSync(imagePath(id));
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

// ---------- shared text ----------

// The count in generated copy comes from the source, so adding an example never leaves it stale.
const COUNT = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'][examples.length] ?? String(examples.length);
const Count = COUNT[0].toUpperCase() + COUNT.slice(1);
const INTRO = `${Count} example designs for the Cookie Compliance banner. Each one is a screenshot of the real widget in preview mode, using one of its real layouts. The build checks body text and headings against the banner colour, and the button label, the selected and unselected level labels and the links against their backgrounds, at WCAG AA (4.5:1).`;

const APPLY = [
  'A `design` block set on your own page is overwritten by your app\'s published configuration a moment after the banner loads. To use one of these designs on a live banner:',
  '',
  '- **Dashboard:** set the same values in your app\'s banner design settings, then publish.',
  '- **MCP server:** call `account.previewDesignChange` with your AppID and the `design` object, show the before/after to the site owner, then call `account.updateDesign` with the same object and the returned `previewToken`.',
  '',
  'Never add a `design` block to the install snippet. To derive a design from your own site\'s colours instead, follow [`skills/match-site-design/SKILL.md`](../skills/match-site-design/SKILL.md).',
];

// ---------- README.md ----------

function readme() {
  const out = [`<!-- ${GENERATED} -->`, '', '# Banner design gallery', '', INTRO, ''];
  for (const ex of examples) {
    out.push(`## ${ex.title}`, '', `![${ex.alt}](img/${ex.id}.png)`, '', ex.caption, '',
      '```json', JSON.stringify(ex.design, null, 2), '```', '');
  }
  out.push('## Apply a design to your live banner', '', ...APPLY, '');
  return out.join('\n');
}

// ---------- index.html ----------

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
// Inline markdown used in the shared text: `code`, **bold**, [text](href).
const md = (s) => esc(s)
  .replace(/\[`([^`]+)`\]\(([^)]+)\)/g, '<a href="$2"><code>$1</code></a>')
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

function applyHtml() {
  const items = APPLY.filter((l) => l.startsWith('- ')).map((l) => `      <li>${md(l.slice(2))}</li>`);
  const paras = APPLY.filter((l) => l && !l.startsWith('- '));
  return [
    `    <p>${md(paras[0])}</p>`,
    '    <ul>', ...items, '    </ul>',
    `    <p>${md(paras[1])}</p>`,
  ].join('\n');
}

function html() {
  const title = 'Banner design gallery — Cookie Compliance';
  const desc = `${Count} example Cookie Compliance consent banner designs, each with a screenshot and the exact design JSON, with text, button, level label and link colours checked against WCAG AA.`;
  const ogImage = `${SITE}img/${examples[0].id}.png`;
  const ogSize = pngSize(examples[0].id);
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ImageGallery',
    name: 'Banner design gallery',
    description: desc,
    url: SITE,
    image: examples.map((ex) => ({
      '@type': 'ImageObject',
      name: ex.title,
      caption: ex.alt,
      contentUrl: `${SITE}img/${ex.id}.png`,
    })),
  };
  const figures = examples.map((ex, i) => {
    const { width, height } = pngSize(ex.id);
    const lazy = i === 0 ? '' : ' loading="lazy"';
    return [
      `    <figure id="${ex.id}">`,
      `      <img src="img/${ex.id}.png" alt="${esc(ex.alt)}" width="${width}" height="${height}"${lazy}>`,
      '      <details>',
      '        <summary>Design JSON</summary>',
      `        <pre><code>${esc(JSON.stringify(ex.design, null, 2))}</code></pre>`,
      '      </details>',
      `      <figcaption><strong>${esc(ex.title)}</strong><span class="desc">${esc(ex.caption)}</span></figcaption>`,
      '    </figure>',
    ].join('\n');
  });
  return `<!doctype html>
<!-- ${GENERATED} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${SITE}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:type" content="website">
<meta property="og:url" content="${SITE}">
<meta property="og:site_name" content="Cookie Compliance Agent Manual">
<meta property="og:image" content="${ogImage}">
<meta property="og:image:alt" content="${esc(examples[0].alt)}">
<meta property="og:image:width" content="${ogSize.width}">
<meta property="og:image:height" content="${ogSize.height}">
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2).replace(/</g, '\\u003c')}
</script>
<style>
  :root {
    color-scheme: light dark;
    --accent: #20c19e;
    --link: #0f7a63; /* #20c19e is 2.29:1 on white; this is 5.27:1 */
    --bg: #ffffff;
    --fg: #1a1f24;
    --muted: #5a6570;
    --border: #e3e7ea;
    --code-bg: rgba(32,193,158,0.1);
    padding-top: env(safe-area-inset-top, 0px);
    padding-bottom: env(safe-area-inset-bottom, 0px);
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg: #14181c;
      --fg: #eef1f3;
      --muted: #9aa5ad;
      --border: #2a3138;
      --code-bg: rgba(32,193,158,0.15);
      --link: #20c19e;
    }
  }
  :root[data-theme="dark"] {
    --bg: #14181c;
    --fg: #eef1f3;
    --muted: #9aa5ad;
    --border: #2a3138;
    --code-bg: rgba(32,193,158,0.15);
    --link: #20c19e;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    line-height: 1.55;
  }
  main {
    max-width: 76rem;
    margin: 0 auto;
    padding: 3rem 1.25rem 4rem;
  }
  h1 { font-size: 1.6rem; margin: 0 0 0.5rem; }
  .tagline { color: var(--muted); margin: 0 0 2rem; font-size: 1.05rem; max-width: 42rem; }
  h2 { font-size: 1.1rem; margin: 2.25rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; }
  a { color: var(--link); text-decoration: none; font-weight: 600; }
  p a, li a, footer a { text-decoration: underline; } /* in-text links: not colour alone */
  a:hover { text-decoration: underline; }
  .back { display: inline-block; margin-bottom: 1.5rem; font-size: 0.92rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 32rem), 1fr)); gap: 2rem; }
  figure { margin: 0; }
  figure img { display: block; width: 100%; height: auto; border: 1px solid var(--border); border-radius: 6px; }
  figcaption { margin: 0.6rem 0 0.4rem; padding-left: 1rem; border-left: 2px solid var(--accent); }
  .desc { display: block; color: var(--muted); font-weight: 400; font-size: 0.92rem; margin-top: 0.15rem; }
  summary { cursor: pointer; color: var(--muted); font-size: 0.9rem; }
  pre { background: var(--code-bg); padding: 0.75rem 1rem; border-radius: 6px; overflow-x: auto; font-size: 0.85rem; }
  code { background: var(--code-bg); padding: 0.1em 0.4em; border-radius: 4px; font-size: 0.9em; }
  pre code { background: none; padding: 0; font-size: inherit; }
  .apply { max-width: 42rem; }
  .apply ul { padding-left: 1.25rem; }
  .apply li { margin: 0.4rem 0; }
  footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.9rem; }
  footer a { font-weight: 400; }
</style>
</head>
<body>
<main>
  <a class="back" href="/">&larr; Cookie Compliance Agent Manual</a>
  <h1>Banner design gallery</h1>
  <p class="tagline">${esc(INTRO)}</p>

  <div class="grid">
${figures.join('\n')}
  </div>

  <section class="apply">
    <h2>Apply a design to your live banner</h2>
${applyHtml()}
  </section>

  <footer>
    Cookie Compliance is a product of <a href="https://hu-manity.co">Hu-manity.co</a>.
    Machine-readable version: <a href="README.md">gallery/README.md</a>.
  </footer>
</main>
</body>
</html>
`;
}

// ---------- build ----------

function build(check) {
  validate({ needImages: true });
  const outputs = { 'README.md': readme(), 'index.html': html() };
  let stale = false;
  for (const [name, content] of Object.entries(outputs)) {
    const path = join(dir, name);
    if (check) {
      if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
        console.error(`stale: gallery/${name} does not match gallery/examples.json (run: node scripts/gallery.mjs build)`);
        stale = true;
      }
    } else {
      writeFileSync(path, content);
    }
  }
  if (stale) process.exit(1);
  console.log(check ? 'gallery: up to date' : 'gallery: wrote gallery/README.md and gallery/index.html');
}

// ---------- render ----------

// A generic placeholder site in the example's own colours, so each screenshot
// shows the banner in context. The widget script is the only external URL.
function mockPage(ex) {
  const { background: bg, text, accent } = ex.site;
  // Mock call-to-action label: black or white, whichever reads better on the accent.
  const ctaText = contrast('#000000', accent) >= contrast('#ffffff', accent) ? '#000000' : '#ffffff';
  const huOptions = { currentLanguage: 'en', blocking: true, globalCookie: false, design: ex.design, previewMode: true };
  const para = 'Hand-picked goods for everyday life, shipped from our small workshop. Every item is checked before it leaves, and every order arrives in recycled packaging.';
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<script>var huOptions = ${JSON.stringify(huOptions)};</script>
<script src="${WIDGET}" charset="utf-8"></script>
<style>
  body { margin: 0; background: ${bg}; color: ${text}; font-family: Georgia, "Times New Roman", serif; }
  header { display: flex; align-items: center; justify-content: space-between; padding: 22px 64px; border-bottom: 1px solid ${text}22; }
  .mark { font-size: 24px; font-weight: 700; letter-spacing: 0.02em; }
  nav a { color: ${text}; text-decoration: none; margin-left: 28px; font-family: system-ui, sans-serif; font-size: 15px; }
  .hero { padding: 72px 64px 40px; max-width: 760px; }
  .hero h1 { font-size: 46px; line-height: 1.15; margin: 0 0 18px; }
  .hero p { font-size: 19px; line-height: 1.6; margin: 0 0 26px; opacity: 0.85; }
  .cta { display: inline-block; background: ${accent}; color: ${ctaText}; padding: 12px 26px; border-radius: 4px; font-family: system-ui, sans-serif; font-weight: 600; }
  .body { padding: 0 64px; max-width: 760px; font-size: 17px; line-height: 1.7; opacity: 0.8; }
</style>
</head>
<body>
<header><span class="mark">Example Store</span><nav><a href="#">Shop</a><a href="#">Journal</a><a href="#">About</a><a href="#">Contact</a></nav></header>
<section class="hero"><h1>Simple things, made well.</h1><p>${para}</p><span class="cta">Browse the collection</span></section>
<section class="body"><p>${para}</p><p>${para}</p><p>${para}</p></section>
</body>
</html>`;
}

async function render(ids) {
  validate({ needImages: false }); // never screenshot a design the build would reject
  let playwright;
  try {
    playwright = createRequire(import.meta.url)('playwright');
  } catch {
    console.error('gallery render needs playwright. Install it with: npm i playwright (then: npx playwright install chromium)');
    process.exit(1);
  }
  const unknown = ids.filter((id) => !examples.some((ex) => ex.id === id));
  if (unknown.length) {
    console.error(`gallery: unknown example id(s): ${unknown.join(', ')}`);
    process.exit(1);
  }
  const chosen = ids.length ? examples.filter((ex) => ids.includes(ex.id)) : examples;
  const browser = await playwright.chromium.launch();
  // The widget does not start for automated browsers: it checks
  // navigator.webdriver and a "HeadlessChrome/" user agent. Present as a normal
  // desktop Chrome so the preview renders.
  const userAgent = `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browser.version()} Safari/537.36`;
  let failed = false;
  try {
    for (const ex of chosen) {
      const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1, userAgent });
      await context.addInitScript(() => Object.defineProperty(Navigator.prototype, 'webdriver', { get: () => false }));
      const page = await context.newPage();
      // Served from a placeholder origin, not page.setContent: about:blank has no
      // cookie access, and the widget stops when reading document.cookie throws.
      await page.route(PAGE_URL, (route) => route.fulfill({ contentType: 'text/html', body: mockPage(ex) }));
      try {
        await page.goto(PAGE_URL, { waitUntil: 'load' });
        // The banner's root container is #hu; wait inside it, not on the document.
        const banner = page.locator('#hu');
        await banner.waitFor({ state: 'visible', timeout: 20000 });
        await banner.locator('button').first().waitFor({ state: 'visible', timeout: 10000 });
        // Let the entrance animation finish: its length plus a margin, at least 1s.
        const speedMs = parseFloat(ex.design.animationSpeed ?? WIDGET_ANIMATION_SPEED) * 1000;
        await page.waitForTimeout(Math.max(1000, speedMs + 500));
        await page.screenshot({ path: imagePath(ex.id) });
        console.log(`rendered gallery/img/${ex.id}.png`);
      } catch (err) {
        console.error(`gallery: banner did not render for "${ex.id}": ${err.message.split('\n')[0]}`);
        failed = true;
      }
      await context.close();
    }
  } finally {
    await browser.close();
  }
  if (failed) process.exit(1);
}

// ---------- main ----------

const [cmd, ...args] = process.argv.slice(2);
if (cmd === 'build') build(args.includes('--check'));
else if (cmd === 'render') await render(args);
else {
  console.error('usage: node scripts/gallery.mjs build [--check] | render [id ...]');
  process.exit(2);
}
