#!/usr/bin/env bash
# Mirrors the repo's markdown into site/ so manual.hu-manity.co serves the
# same skills/cookbooks/llms.txt and design gallery as raw files, at stable
# paths. site/ is a generated copy: edit the source (skills/, cookbooks/,
# gallery/examples.json, root files), never site/ directly.
#
#   scripts/sync-site.sh          rebuild the site/ mirror
#   scripts/sync-site.sh --check  exit 1 if the mirror is out of date (for CI)
set -euo pipefail
shopt -s nullglob
root="$(cd "$(dirname "$0")/.." && pwd)"
check=false
[ "${1:-}" = "--check" ] && check=true

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
chmod 755 "$tmp"

for f in README.md AGENTS.md LICENSE; do
  cp "$root/$f" "$tmp/$f"
done
# llms.txt says "this repo" -- true on GitHub, not on this site. One
# deliberate, mechanical substitution; everything else is a byte-identical
# mirror.
sed 's/this repo is the agent-facing companion/this manual is the agent-facing companion/' \
  "$root/llms.txt" > "$tmp/llms.txt"

mkdir -p "$tmp/skills" "$tmp/cookbooks"
for skill_md in "$root"/skills/*/SKILL.md; do
  name="$(basename "$(dirname "$skill_md")")"
  mkdir -p "$tmp/skills/$name"
  cp "$skill_md" "$tmp/skills/$name/SKILL.md"
done
for cookbook in "$root"/cookbooks/*.md; do
  cp "$cookbook" "$tmp/cookbooks/$(basename "$cookbook")"
done
# The design gallery: generated by scripts/gallery.mjs, mirrored as-is.
mkdir -p "$tmp/gallery/img"
cp "$root/gallery/README.md" "$root/gallery/index.html" "$tmp/gallery/"
for img in "$root"/gallery/img/*.png; do
  cp "$img" "$tmp/gallery/img/$(basename "$img")"
done
# The top-level site/index.html is hand-written, not part of the mirror: carry
# it into the expected tree so the diff exempts it (and only it), and so a
# rebuild keeps it. Any other index.html (e.g. site/gallery/) is mirrored.
cp "$root/site/index.html" "$tmp/index.html"

if $check; then
  stale=0
  if ! diff -rq "$tmp" "$root/site" >/dev/null 2>&1; then
    echo "stale: site/ does not match skills/, cookbooks/, gallery/ and root docs"
    diff -rq "$tmp" "$root/site" || true
    stale=1
  fi
  exit $stale
else
  find "$root/site" -mindepth 1 -delete
  cp -r "$tmp"/. "$root/site"/
  echo "synced site/"
fi
